### ISSUE TITLE
[Bug] Compilation failure: _MdiIconData extends final class IconData in Flutter 3.47.5 (Dart 3.13)

### ISSUE THREAD

**Issue by ItsWachira** [ziofat/material_design_icons_flutter#69]
<html><head></head><body><h3 data-path-to-node="2" style="font-family: &quot;Google Sans&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important;">Summary</h3><p data-path-to-node="3" style="font-family: &quot;Google Sans Text&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important;">The <code data-path-to-node="3" data-index-in-node="4" style="font-family: &quot;Google Sans Text&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important;">material_design_icons_flutter</code> package (v7.0.7296) fails to compile on Flutter 3.47.5 (Dart 3.13.4). The Flutter framework recently made <code data-path-to-node="3" data-index-in-node="140" style="font-family: &quot;Google Sans Text&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important;">IconData</code> a <code data-path-to-node="3" data-index-in-node="151" style="font-family: &quot;Google Sans Text&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important;">final</code> class, meaning it can no longer be extended outside of its own library. The package's internal <code data-path-to-node="3" data-index-in-node="252" style="font-family: &quot;Google Sans Text&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important;">_MdiIconData</code> class attempts to extend <code data-path-to-node="3" data-index-in-node="290" style="font-family: &quot;Google Sans Text&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important;">IconData</code>, which now triggers a compilation error.</p><h3 data-path-to-node="4" style="font-family: &quot;Google Sans&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important;">Error</h3><response-element class="no-md" ng-version="0.0.0-PLACEHOLDER" style="font-family: &quot;Google Sans Text&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important;"><!----><!----><!----><!----><!----><!----><code-block _nghost-ng-c2076467543="" class="ng-tns-c2076467543-13 ng-star-inserted" style="font-family: &quot;Google Sans Text&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important;"><!----><!----><div _ngcontent-ng-c2076467543="" class="code-block ng-tns-c2076467543-13 ng-animate-disabled ng-trigger ng-trigger-codeBlockRevealAnimation" jslog="223238;track:impression,attention;BardVeMetadataKey:W1sicl81OGMxYWFlMTIwNTFmY2ZjIiwiY182MTVlMzAzY2IyZjI4MDhhIixudWxsLCJyY19kY2FmYWIxZWI5NDRmYTk4IixudWxsLG51bGwsImVuIixudWxsLDEsbnVsbCxudWxsLDEsMF1d" data-hveid="0" decode-data-ved="1" data-ved="0CAAQhtANahcKEwiG9NPFzP-WAxUAAAAAHQAAAAAQKA" style="display: block; font-family: &quot;Google Sans Text&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important;"><div _ngcontent-ng-c2076467543="" class="code-block-decoration header-formatted gds-title-s hide-on-print ng-tns-c2076467543-13 ng-star-inserted" style="font-family: &quot;Google Sans Text&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important;"><span _ngcontent-ng-c2076467543="" class="ng-tns-c2076467543-13" style="font-family: &quot;Google Sans Text&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important;">Plaintext</span><div _ngcontent-ng-c2076467543="" class="buttons ng-tns-c2076467543-13 ng-star-inserted" style="font-family: &quot;Google Sans Text&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important;"><!----><button _ngcontent-ng-c2076467543="" aria-label="Download code" mat-icon-button="" gemtooltip="Download code" class="mdc-icon-button mat-mdc-icon-button mat-mdc-button-base mat-mdc-tooltip-trigger download-button ng-tns-c2076467543-13 mat-unthemed ng-star-inserted" mat-ripple-loader-uninitialized="" mat-ripple-loader-class-name="mat-mdc-button-ripple" mat-ripple-loader-centered="" style="font-family: &quot;Google Sans Text&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important;"><span class="mat-mdc-button-persistent-ripple mdc-icon-button__ripple" style="font-family: &quot;Google Sans Text&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important;"></span><mat-icon _ngcontent-ng-c2076467543="" role="img" fonticon="download" class="mat-icon notranslate gds-icon-s google-symbols mat-ligature-font mat-icon-no-color" aria-hidden="true" data-mat-icon-type="font" data-mat-icon-name="download" style="font-family: &quot;Google Sans Text&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important;"></mat-icon><!----><span class="mat-focus-indicator" style="font-family: &quot;Google Sans Text&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important;"></span><span class="mat-mdc-button-touch-target" style="font-family: &quot;Google Sans Text&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important;"></span></button><!----><!----><!----><!----><!----><button _ngcontent-ng-c2076467543="" aria-label="Copy code" mat-icon-button="" gemtooltip="Copy code" class="mdc-icon-button mat-mdc-icon-button mat-mdc-button-base mat-mdc-tooltip-trigger copy-button ng-tns-c2076467543-13 mat-unthemed ng-star-inserted" mat-ripple-loader-uninitialized="" mat-ripple-loader-class-name="mat-mdc-button-ripple" mat-ripple-loader-centered="" jslog="179062;track:generic_click,impression;BardVeMetadataKey:W1sicl81OGMxYWFlMTIwNTFmY2ZjIiwiY182MTVlMzAzY2IyZjI4MDhhIixudWxsLCJyY19kY2FmYWIxZWI5NDRmYTk4IixudWxsLG51bGwsImVuIixudWxsLDEsbnVsbCxudWxsLDEsMF1d;mutable:true" style="font-family: &quot;Google Sans Text&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important;"><span class="mat-mdc-button-persistent-ripple mdc-icon-button__ripple" style="font-family: &quot;Google Sans Text&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important;"></span><mat-icon _ngcontent-ng-c2076467543="" role="img" fonticon="content_copy" class="mat-icon notranslate gds-icon-s google-symbols mat-ligature-font mat-icon-no-color" aria-hidden="true" data-mat-icon-type="font" data-mat-icon-name="content_copy" style="font-family: &quot;Google Sans Text&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important;"></mat-icon><!----><span class="mat-focus-indicator" style="font-family: &quot;Google Sans Text&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important;"></span><span class="mat-mdc-button-touch-target" style="font-family: &quot;Google Sans Text&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important;"></span></button><!----><!----><!----></div><!----><!----></div><!----><div _ngcontent-ng-c2076467543="" class="formatted-code-block-internal-container ng-tns-c2076467543-13" style="font-family: &quot;Google Sans Text&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important;"><div _ngcontent-ng-c2076467543="" class="animated-opacity ng-tns-c2076467543-13" style="font-family: &quot;Google Sans Text&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important;"><!----><pre _ngcontent-ng-c2076467543="" class="ng-tns-c2076467543-13" style="font-family: &quot;Google Sans Text&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important;"><code _ngcontent-ng-c2076467543="" role="text" data-test-id="code-content" class="code-container formatted ng-tns-c2076467543-13 embedded" style="font-family: &quot;Google Sans Text&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important;">../../../.pub-cache/hosted/pub.dev/material_design_icons_flutter-7.0.7296/lib/icon_map.dart:7302:28: Error: The class 'IconData' can't be extended outside of its library because it's a final class. 
class _MdiIconData extends IconData { 
                           ^ 
Target kernel_snapshot_program failed: Exception
</code></pre><!----></div></div></div><!----><!----><!----></code-block><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----></response-element><h3 data-path-to-node="6" style="font-family: &quot;Google Sans&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important;"><span class="citation-730" style="font-family: &quot;Google Sans Text&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important;"></span><span class="citation-729 citation-730" style="font-family: &quot;Google Sans Text&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important;"></span><span class="citation-728 citation-729 citation-730" style="font-family: &quot;Google Sans Text&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important;"></span><span class="citation-727 citation-728 citation-729 citation-730 citation-end-730" style="font-family: &quot;Google Sans Text&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important;">Environment<source-footnote ng-version="0.0.0-PLACEHOLDER" _nghost-ng-c583429416="" style="font-family: &quot;Google Sans Text&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important;"><sup _ngcontent-ng-c583429416="" class="superscript embedded" data-turn-source-index="1" style="font-family: &quot;Google Sans Text&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important; font-size: 16px !important; background-color: transparent !important;"><!----></sup></source-footnote></span><span class="citation-727 citation-728 citation-729 citation-end-729" style="font-family: &quot;Google Sans Text&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important;"><source-footnote ng-version="0.0.0-PLACEHOLDER" _nghost-ng-c583429416="" style="font-family: &quot;Google Sans Text&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important;"><sup _ngcontent-ng-c583429416="" class="superscript embedded" data-turn-source-index="2" style="font-family: &quot;Google Sans Text&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important; font-size: 16px !important; background-color: transparent !important;"><!----></sup></source-footnote></span><span class="citation-727 citation-728 citation-end-728" style="font-family: &quot;Google Sans Text&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important;"><source-footnote ng-version="0.0.0-PLACEHOLDER" _nghost-ng-c583429416="" style="font-family: &quot;Google Sans Text&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important;"><sup _ngcontent-ng-c583429416="" class="superscript embedded" data-turn-source-index="3" style="font-family: &quot;Google Sans Text&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important; font-size: 16px !important; background-color: transparent !important;"><!----></sup></source-footnote></span><span class="citation-727 citation-end-727" style="font-family: &quot;Google Sans Text&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important;"><source-footnote ng-version="0.0.0-PLACEHOLDER" _nghost-ng-c583429416="" style="font-family: &quot;Google Sans Text&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important;"><sup _ngcontent-ng-c583429416="" class="superscript embedded" data-turn-source-index="4" style="font-family: &quot;Google Sans Text&quot;, sans-serif !important; line-height: 1.15 !important; margin-top: 0px !important; margin-left: 0px !important; margin-right: 0px !important; font-size: 16px !important; background-color: transparent !important;"><!----></sup></source-footnote></span></h3>
Property | Value
-- | --
Flutter | 3.47.5 (stable)
Dart | 3.13.4
Package version | 7.0.72

</body></html>
